[2022-08-03 17:09:40,327] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.drop_table manual__2022-08-03T17:09:34.814144+00:00 [queued]>
[2022-08-03 17:09:40,344] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.drop_table manual__2022-08-03T17:09:34.814144+00:00 [queued]>
[2022-08-03 17:09:40,348] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 17:09:40,351] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 17:09:40,355] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 17:09:40,383] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): drop_table> on 2022-08-03 17:09:34.814144+00:00
[2022-08-03 17:09:40,397] {standard_task_runner.py:52} INFO - Started process 2968 to run task
[2022-08-03 17:09:40,402] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'drop_table', 'manual__2022-08-03T17:09:34.814144+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmp4ycsn5to', '--error-file', '/tmp/tmp2azk05rw']
[2022-08-03 17:09:40,409] {standard_task_runner.py:80} INFO - Job 90: Subtask drop_table
[2022-08-03 17:09:40,543] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.drop_table manual__2022-08-03T17:09:34.814144+00:00 [running]> on host 3b0f05b8acbc
[2022-08-03 17:09:40,681] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=drop_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T17:09:34.814144+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T17:09:34.814144+00:00
[2022-08-03 17:09:40,714] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-03 17:09:40,738] {dbapi.py:231} INFO - Running statement: DROP TABLE vehicles, parameters: None
[2022-08-03 17:09:40,753] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: table "vehicles" does not exist

[2022-08-03 17:09:40,807] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=ltv-pipeline, task_id=drop_table, execution_date=20220803T170934, start_date=20220803T170940, end_date=20220803T170940
[2022-08-03 17:09:40,840] {standard_task_runner.py:97} ERROR - Failed to execute job 90 for task drop_table (table "vehicles" does not exist
; 2968)
[2022-08-03 17:09:40,911] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-03 17:09:41,017] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
