[2022-08-03 17:19:14,136] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.pre-process manual__2022-08-03T17:17:43.903702+00:00 [queued]>
[2022-08-03 17:19:14,167] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.pre-process manual__2022-08-03T17:17:43.903702+00:00 [queued]>
[2022-08-03 17:19:14,174] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 17:19:14,195] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 17:19:14,214] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 17:19:14,271] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): pre-process> on 2022-08-03 17:17:43.903702+00:00
[2022-08-03 17:19:14,305] {standard_task_runner.py:52} INFO - Started process 3358 to run task
[2022-08-03 17:19:14,311] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'pre-process', 'manual__2022-08-03T17:17:43.903702+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmpelxvdry2', '--error-file', '/tmp/tmpv27729t8']
[2022-08-03 17:19:14,331] {standard_task_runner.py:80} INFO - Job 97: Subtask pre-process
[2022-08-03 17:19:14,460] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.pre-process manual__2022-08-03T17:17:43.903702+00:00 [running]> on host 3b0f05b8acbc
[2022-08-03 17:19:14,571] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=pre-process
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T17:17:43.903702+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T17:17:43.903702+00:00
[2022-08-03 17:19:14,581] {logging_mixin.py:115} INFO - To avoid adding sh files to the container I added some subprocess to mimic a shell script
[2022-08-03 17:19:14,633] {logging_mixin.py:115} INFO - Line Count:  gzip: files/vehicle_challenge.csv.gz: No such file or directory
0
[2022-08-03 17:19:14,702] {logging_mixin.py:115} INFO - Columns Count:  21
[2022-08-03 17:19:14,785] {logging_mixin.py:115} INFO - Headers:  id,vin,price,miles,stock_no,year,make,model,trim,body_type,vehicle_type,drivetrain,transmission,fuel_type,engine_size,engine_block,seller_name,street,city,state,zip
[2022-08-03 17:19:14,799] {logging_mixin.py:115} INFO - This is a python solution
[2022-08-03 17:19:14,861] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-test.py", line 61, in _preprocess_data
    df = pd.read_csv('files/vehicle_challenge.csv.gz')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 645, in get_handle
    **compression_args,
  File "/usr/local/lib/python3.7/gzip.py", line 168, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'files/vehicle_challenge.csv.gz'
[2022-08-03 17:19:14,996] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=ltv-pipeline, task_id=pre-process, execution_date=20220803T171743, start_date=20220803T171914, end_date=20220803T171914
[2022-08-03 17:19:15,093] {standard_task_runner.py:97} ERROR - Failed to execute job 97 for task pre-process ([Errno 2] No such file or directory: 'files/vehicle_challenge.csv.gz'; 3358)
[2022-08-03 17:19:15,147] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-03 17:19:15,232] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
