[2022-08-03 15:33:58,579] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.drop_table manual__2022-08-03T15:33:47.485374+00:00 [queued]>
[2022-08-03 15:33:58,640] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.drop_table manual__2022-08-03T15:33:47.485374+00:00 [queued]>
[2022-08-03 15:33:58,642] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 15:33:58,645] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 15:33:58,658] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 15:33:58,754] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): drop_table> on 2022-08-03 15:33:47.485374+00:00
[2022-08-03 15:33:58,821] {standard_task_runner.py:52} INFO - Started process 738 to run task
[2022-08-03 15:33:58,863] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'drop_table', 'manual__2022-08-03T15:33:47.485374+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmpg7xg96ak', '--error-file', '/tmp/tmp4tw3sdg6']
[2022-08-03 15:33:58,887] {standard_task_runner.py:80} INFO - Job 33: Subtask drop_table
[2022-08-03 15:33:59,525] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.drop_table manual__2022-08-03T15:33:47.485374+00:00 [running]> on host 3b0f05b8acbc
[2022-08-03 15:33:59,835] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=drop_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T15:33:47.485374+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T15:33:47.485374+00:00
[2022-08-03 15:33:59,870] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-03 15:33:59,888] {dbapi.py:231} INFO - Running statement: DROP TABLE vehicules, parameters: None
[2022-08-03 15:33:59,902] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedTable: table "vehicules" does not exist

[2022-08-03 15:33:59,940] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=ltv-pipeline, task_id=drop_table, execution_date=20220803T153347, start_date=20220803T153358, end_date=20220803T153359
[2022-08-03 15:33:59,962] {standard_task_runner.py:97} ERROR - Failed to execute job 33 for task drop_table (table "vehicules" does not exist
; 738)
[2022-08-03 15:34:00,019] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-03 15:34:00,200] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
