[2022-08-03 16:21:55,801] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.load-data manual__2022-08-03T16:21:39.128344+00:00 [queued]>
[2022-08-03 16:21:55,815] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: ltv-pipeline.load-data manual__2022-08-03T16:21:39.128344+00:00 [queued]>
[2022-08-03 16:21:55,818] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 16:21:55,822] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-03 16:21:55,825] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-03 16:21:55,843] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): load-data> on 2022-08-03 16:21:39.128344+00:00
[2022-08-03 16:21:55,854] {standard_task_runner.py:52} INFO - Started process 1040 to run task
[2022-08-03 16:21:55,861] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'ltv-pipeline', 'load-data', 'manual__2022-08-03T16:21:39.128344+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/dag-test.py', '--cfg-path', '/tmp/tmp2x6si5p7', '--error-file', '/tmp/tmpiorap0jx']
[2022-08-03 16:21:55,868] {standard_task_runner.py:80} INFO - Job 67: Subtask load-data
[2022-08-03 16:21:55,983] {task_command.py:371} INFO - Running <TaskInstance: ltv-pipeline.load-data manual__2022-08-03T16:21:39.128344+00:00 [running]> on host 3b0f05b8acbc
[2022-08-03 16:21:56,075] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ltv-pipeline
AIRFLOW_CTX_TASK_ID=load-data
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T16:21:39.128344+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T16:21:39.128344+00:00
[2022-08-03 16:21:56,101] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-08-03 16:21:56,120] {dbapi.py:231} INFO - Running statement: COPY vehicles FROM 'files/vehicle_challenge.csv' WITH DELIMITER ',' CSV HEADER;, parameters: None
[2022-08-03 16:21:56,132] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag-test.py", line 55, in insert_data
    post_hook.run("""COPY vehicles FROM 'files/vehicle_challenge.csv' WITH DELIMITER ',' CSV HEADER;""")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 211, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 235, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "files/vehicle_challenge.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2022-08-03 16:21:56,183] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=ltv-pipeline, task_id=load-data, execution_date=20220803T162139, start_date=20220803T162155, end_date=20220803T162156
[2022-08-03 16:21:56,203] {standard_task_runner.py:97} ERROR - Failed to execute job 67 for task load-data (could not open file "files/vehicle_challenge.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 1040)
[2022-08-03 16:21:56,244] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-03 16:21:56,344] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
